repository: softmaterialslab/np-assembly-lab

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: Nanoparticle Assembly Lab
# this appears on the top navigation bar next to the home button

site_title: Nanoparticle Assembly Lab
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

exclude:
  - .idea/
  - .gitignore
# these are the files and directories that jekyll will exclude from the build

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
